default_assignment_8 = {'key_assignment':{'kick':[36,37],
                                          'snr':38,
                                          'stick':39,
                                          'clp':40,
                                          'tom':[41,42],
                                          'shk':43,
                                          'ped':44,
                                          'hhc':45,
                                          'cym':46,                                          
                                          'hho':47},
                        'repeat_octive':[-1,1]} 

default_assignment_24 = {'key_assignment':{'kick':[36,37],
                                          'snr':[38,50],
                                          'stick':39,
                                          'clp':40,
                                          'tom':[41,42],
                                          'shk':43,
                                          'ped':44,
                                          'hhc':45,
                                          'cym':46,                                          
                                          'hho':47,
                                          # repeat
                                          'taik':48,
                                          'bass':49,
                                          #'snr2':50,
                                          'rim':51,
                                          'cah':52,
                                          'tomf':53,#,42],
                                          'tab':54,
                                          'whis':55,
                                          'met':56,
                                          'wood':57,
                                          'rid':58,                                          
                                          'tri':59},
                           'repeat_octive':[-1,1]} 

default_assignment_36 = {'key_assignment':{'kick':[36,37,24,25],
                                          'snr':[38,50,26],
                                          'stick':[39,27],
                                          'clp':[40,28],
                                          'tom':[41,42,29,30],
                                          'shk':[43,31],
                                          'ped':[44,32],
                                          'hhc':[45,33],
                                          'cym':[46,34],                                          
                                          'hho':[47,35],
                                          # repeat
                                          'taik':48,
                                          'bass':49,
                                          #'snr2':50,
                                          'rim':51,
                                          'cah':52,
                                          'tomf':53,#,42],
                                          'tab':54,
                                          'whis':55,
                                          'met':56,
                                          'wood':57,
                                          'rid':58,                                          
                                          'tri':59},
                        'repeat_octive':[-1,1]} 

# default parameters
PARAMS_SAMPLE_DEFAULT = {("1","GEN1_REVERSE"):0,
                         ("2","GEN1_GROUP"):0,
                         ("3","GEN1_COARSE"):0,
                         ("4","GEN1_FINE"):0,
                         ("5","GEN1_ENVTIME"):0.2,
                         ("6","DCF1_CUTOFF"):1,
                         ("7","DCF1_RESO"):0,
                         ("8","DCF1_TYPE"):0,
                         ("9","DCF1_SLOPE"):0,
                         ("10","DCF1_ENVELOPE"):1,
                         ("11","DCF1_ATTACK"):0,
                         ("12","DCF1_DECAY1"):0.5,
                         ("13","DCF1_LEVEL2"):0.2,
                         ("14","DCF1_DECAY2"):0.5,
                         ("15","LFO1_SHAPE"):1,
                         ("16","LFO1_WIDTH"):1,
                         ("17","LFO1_RATE"):0.5,
                         ("18","LFO1_SWEEP"):0,
                         ("19","LFO1_PITCH"):0,
                         ("20","LFO1_CUTOFF"):0,
                         ("21","LFO1_RESO"):0,
                         ("22","LFO1_PANNING"):0,
                         ("23","LFO1_VOLUME"):0,
                         ("24","LFO1_ATTACK"):0,
                         ("25","LFO1_DECAY1"):0.5,
                         ("26","LFO1_LEVEL2"):0.2,
                         ("27","LFO1_DECAY2"):0.5,
                         ("28","DCA1_VOLUME"):0.6,
                         ("29","DCA1_ATTACK"):0,
                         ("30","DCA1_DECAY1"):0.5,
                         ("31","DCA1_LEVEL2"):0.2,
                         ("32","DCA1_DECAY2"):0.5,
                         ("33","OUT1_WIDTH"):0.2,
                         ("34","OUT1_PANNING"):0,
                         ("35","OUT1_VOLUME"):0.5}

PARAMS_INSTRUMENT_DEFAULT = {("36","DEF1_PITCHBEND"):0.2,
                             ("37","DEF1_MODWHEEL"):0.2,
                             ("38","DEF1_PRESSURE"):0.2,
                             ("39","DEF1_VELOCITY"):0.59,
                             ("40","DEF1_CHANNEL"):0,
                             ("41","DEF1_NOTEOFF"):1,
                             ("42","CHO1_WET"):0,
                             ("43","CHO1_DELAY"):0.5,
                             ("44","CHO1_FEEDB"):0.5,
                             ("45","CHO1_RATE"):0.5,
                             ("46","CHO1_MOD"):0.5,
                             ("47","FLA1_WET"):0,
                             ("48","FLA1_DELAY"):0.5,
                             ("49","FLA1_FEEDB"):0.5,
                             ("50","FLA1_DAFT"):0,
                             ("51","PHA1_WET"):0,
                             ("52","PHA1_RATE"):0.5,
                             ("53","PHA1_FEEDB"):0.5,
                             ("54","PHA1_DEPTH"):0.5,
                             ("55","PHA1_DAFT"):0,
                             ("56","DEL1_WET"):0,
                             ("57","DEL1_DELAY"):0.5,
                             ("58","DEL1_FEEDB"):0.5,
                             ("59","DEL1_BPM"):180,
                             ("60","DEL1_BPMSYNC"):1,
                             ("61","DEL1_BPMHOST"):180,
                             ("62","REV1_WET"):0,
                             ("63","REV1_ROOM"):0.5,
                             ("64","REV1_DAMP"):0.5,
                             ("65","REV1_FEEDB"):0.5,
                             ("66","REV1_WIDTH"):0,
                             ("67","DYN1_COMPRESS"):1,
                             ("68","DYN1_LIMITER"):0}

PARAMS_SAMPLE_RANDOM_DEFAULT = {("6","DCF1_CUTOFF"):(0.7,1), ("7","DCF1_RESO"):(0,0.3), ("34", "OUT1_PANNING"):(-0.5,0.5), ("34", "OUT1_WIDTH"):(-0.5,0.5), ("24", "LFO1_PITCH"):(-0.1,0.1), ("25", "LFO1_CUTOFF"):(-0.1,0.1), ("27", "LFO1_PANNING"):(-0.1,0.1), ("28", "LFO1_VOLUME"):(-0.5,0.5), ("29", "LFO1_ATTACK"):(-0.5,0.5)}

DEFAULT_ASSIGNMENT = default_assignment_24
